# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

def sum_of_even_fib(num):
  first = 0
  second = 1
  fib_next = 0
  sum = 0
  while(fib_next <= num):
    if(fib_next%2==0):
      sum += fib_next
    fib_next = first + second
    first = second
    second = fib_next
  return sum

def main():
  num = int(input("Please enter the limit "))
  print(sum_of_even_fib(num))
  
if __name__ == '__main__':
  main()